feat: Authentication - refresh access token endpoint
hngprojects/hng_boilerplate_nestjs pull request #356
Opened 2024-07-24 01:31 UTC by King-AJr

## What does this PR do?

This PR implements a new endpoint for refreshing access tokens using a refresh token in the NestJS application. It includes:

- **Added `POST /auth/token/refresh` Endpoint**: Allows clients to obtain a new access token using a valid refresh token.
- **Response Handling**: Provides appropriate responses for missing or invalid refresh tokens.
- **Error Handling**: Returns specific HTTP status codes and messages based on token validity.

## How should this be manually tested?

1. **Register a User**:
   - Use the `POST /auth/register` endpoint to register a new user.

2. **Generate Access and Refresh Tokens**:
   - After registration, ensure you obtain the access token and refresh token.

3. **Refresh Access Token**:
   - Make a `POST` request to `/auth/token/refresh` with the refresh token in the request body.
   - Verify that you receive a new access token if the refresh token is valid.
   - Check the response for appropriate status codes and messages if the refresh token is missing or invalid.

4. **Edge Cases**:
   - Test with an invalid or expired refresh token to ensure the endpoint returns a `401 Unauthorized` status with the correct message.
   - Test without including a refresh token in the request body to confirm a `400 Bad Request` status is returned.

## Checklist

- [x] Implemented `POST /auth/token/refresh` endpoint in the `auth.controller.ts`.
- [x] Added `refreshAccessToken` method in the `AuthenticationService`.
- [x] Updated `AuthenticationService` to handle refresh token validation and generation of new access tokens.
- [x] Modified `auth.controller.ts` to provide appropriate responses for various cases.
- [x] Updated sign up route to return refresh token on user sign up. 
- [x] Tested endpoint functionality to ensure it correctly handles valid and invalid tokens.
- [x] Added appropriate HTTP status codes and response messages for edge cases.
- [x] Added test for this endpoint

2024-07-24 09:04 UTC, King-AJr commented
@TheCodeGhinux I need your review on this. Thanks

2024-07-24 09:19 UTC, King-AJr commented
@Homoakin619 I need your review on this PR.

2024-07-24 09:58 UTC, davidolanrewaju commented
Nicely done, but please include your documentations

2024-07-24 10:18 UTC, Homoakin619 commented on src/modules/auth/auth.controller.ts
move the business logics here into a service such as the authservice, you should have just a line or two in your controller

2024-07-24 11:49 UTC, King-AJr commented
@Cobidex @Homoakin619 I've added a secret for the refresh token and transferred the logic to the service

2024-07-24 13:48 UTC, King-AJr commented
> Well done. Please resolve merge conflicts

I've resolved the conflicts

2024-07-24 16:33 UTC, Cobidex commented on src/modules/auth/auth.service.ts
> +    return this.jwtService.sign(
Well done on the implementation. the only issue i see is the storage of user personal information in the jwt token, its not best practice security wise. its better to have only the user id in it.

2024-07-24 16:51 UTC, Cobidex submitted a review, later dismissed
In line with best practices it's better to store only the id in jwt tokens. Personal identifiers of the user such as email should not be in the token

2024-07-24 17:13 UTC, King-AJr commented
@buka4rill greetings chief I need your review on this PR

2024-07-24 18:34 UTC, Heba-WebDev commented on package.json
Please remove the double nodemailer dependencies

2024-07-24 18:36 UTC, Heba-WebDev requested changes
Please remove the nodemailer dependency and make sure you didn't do the same with passport (I see you installed it and I think it was installed before)

2024-07-24 18:42 UTC, Heba-WebDev approved these changes

2024-07-24 19:22 UTC, buka4rill reviewed
Looks ok but fix conflicts

2024-07-25 00:04 UTC, King-AJr commented
@buka4rill I've dealt with the conflicts

2024-07-25 10:47 UTC, Heba-WebDev commented
@King-AJr You still have conflicts (probably new) so please fix it

2024-07-25 11:07 UTC, King-AJr commented
> @King-AJr You still have conflicts (probably new) so please fix it

@Heba-WebDev check again

2024-07-25 11:26 UTC, King-AJr commented
@buka4rill I've dealt with the new merge conflicts

2024-07-31 12:44 UTC, closed without merging