feat: Organisation - Get By ID
hngprojects/hng_boilerplate_nestjs pull request #386
Opened 2024-07-24 19:35 UTC by Okeke12nancy

## What does the PR do?

This PR implements an endpoint to retrieve the details of an organisation by its ID.

## How should this be manually tested?

1. **Send a GET request** to `/api/v1/organisations/:id`, replacing `:id` with the ID of the organisation you want to retrieve.
2. **Include the Authorization header** with a valid JWT token.

## Request

- **Method**: `GET`
- **URL**: `/api/v1/organisations/:id`
  - Replace `:id` with the actual ID of the organisation.

- **Headers**:
  - `Authorization`: `Bearer <token>`

- **Example Request**:
  ```http
  GET /api/v1/organisations/57868c3f-9605-415c-8e73-cd0a6a4eefa2
  Authorization: Bearer your_jwt_token_here
  ```

### Response

#### Success (200 OK)

- **Status Code**: `200 OK`
- **Content-Type**: `application/json`

- **Response Body**:
  ```json
  {
    "id": "57868c3f-9605-415c-8e73-cd0a6a4eefa2",
    "created_at": "2024-07-24T19:31:33.671Z",
    "updated_at": "2024-07-24T19:31:33.671Z",
    "name": "Nancy",
    "description": "This is a private org",
    "email": "quonepeimme@yopmail.com",
    "industry": "e-commerce",
    "type": "secret",
    "country": "Nigeria",
    "address": "yaba",
    "state": "lags",
    "isDeleted": false,
    "owner": {
      "id": "3f2700fd-39bb-4910-bb0d-f74d14d2bc4a",
      "created_at": "2024-07-24T19:30:43.559Z",
      "updated_at": "2024-07-24T19:30:43.559Z",
      "first_name": "Nancy",
      "last_name": "Okeke",
      "email": "quonepeimme@yopmail.com",
      "password": "$2b$10$UUTxE.cJJm3QY57kBg0VNeYqhqNT7IpOCIghGpYiInbLuXq9ehMHi",
      "is_active": true,
      "attempts_left": null,
      "time_left": null,
      "user_type": "vendor"
    }
  }
  ```

#### Error (404 Not Found)

- **Status Code**: `404 Not Found`
- **Content-Type**: `application/json`

- **Response Body**:
  ```json
  {
    "statusCode": 404,
    "message": "Organisation not found",
    "error": "Not Found"
  }
  ```

#### Error (400 Bad Request) - Invalid ID

- **Status Code**: `400 Bad Request`
- **Content-Type**: `application/json`

- **Response Body**:
  ```json
  {
    "statusCode": 400,
    "message": "Invalid organisation ID format",
    "error": "Bad Request"
  }
  ```

### Checklist of what you did

- [x] Implemented endpoint to get organisation by ID
- [x] Validated organisation ID and handled errors for invalid or non-existent IDs
- [x] Retrieved organisation details from the database
- [x] Returned the organisation details in the response payload
- [x] Implemented error handling for cases where the organisation is not found or the ID is invalid
- [x] Added authentication requirement for the endpoint

### Reference Issue

- **[FEAT]: Organisation - Get By ID**

2024-07-24 22:27 UTC, davidolanrewaju approved these changes

2024-07-24 22:59 UTC, Cobidex commented on .vscode/settings.json
> -    "panel.border": "#333d2a",
Why tamper with the settings though

2024-07-24 22:59 UTC, Cobidex commented on src/database/data-source.ts
> +  port: 5433,
Please remove. Previous settings allows it to connect on the default port of postgres which is 5432. Better change will be:
port: process.env.DB_PORT || 5432

2024-07-24 22:59 UTC, Cobidex commented on src/guards/auth.guard.ts
> +      console.log('Token:', token);
Remove console log since it's served it's debugging function

2024-07-24 22:59 UTC, Cobidex commented on src/modules/organisations/organisations.controller.ts
> +  //// Get Organisation by ID started here
Dangling comments, best removed

2024-07-24 22:59 UTC, Cobidex commented on src/modules/organisations/organisations.service.ts
> +  //// Get Organisation by ID started here
Dangling comments best removed

2024-07-24 23:31 UTC, Okeke12nancy commented
@Cobidex i have made the changes, please go through it again

2024-07-25 05:39 UTC, Cobidex submitted a review, later dismissed

2024-07-27 20:12 UTC, Heba-WebDev commented
Please remove the db/migration files. It's no longer allowed to include migration files in any PR

2024-07-28 18:45 UTC, davidolanrewaju commented on db/migrations/1721833967585-migration.ts
> +import { MigrationInterface, QueryRunner } from 'typeorm';
Remove your migration files

2024-07-28 22:47 UTC, Okeke12nancy commented
@Cobidex @TheCodeGhinux , i have made the necessary changes

2024-07-28 22:57 UTC, Okeke12nancy commented
@davidolanrewaju can you merge already

2024-07-28 23:00 UTC, Heba-WebDev commented on config/index.js
Please remove // eslint-disable-next-line @typescript-eslint/no-var-requires

2024-07-28 23:01 UTC, Heba-WebDev commented on package.json
What's cross-env doing?

2024-07-28 23:03 UTC, Heba-WebDev commented on src/modules/organisations/organisations.controller.ts
Doesn't the organization include user information like password? Why return that all?

2024-07-28 23:05 UTC, Heba-WebDev commented
Left you few comments, please take a look.

2024-07-29 00:02 UTC, Okeke12nancy commented
@Heba-WebDev please check again

2024-07-29 00:37 UTC, Heba-WebDev approved these changes

2024-07-29 00:38 UTC, davidolanrewaju submitted a review, later dismissed

2024-07-29 00:41 UTC, Heba-WebDev requested changes
Please remove .env.local

2024-07-29 01:11 UTC, Heba-WebDev approved these changes

2024-07-29 01:11 UTC, davidolanrewaju approved these changes

2024-07-29 05:33 UTC, Cobidex approved these changes

2024-08-05 16:15 UTC, closed without merging