Feat/forgot password endpoint
hngprojects/hng_boilerplate_nestjs pull request #390
Opened 2024-07-24 19:53 UTC by alexindevs

## Description

This pull request adds the forgot password functionality to the authentication module. It includes the following changes:

- Added `forgotPassword` method in `AuthService`.
- Added `forgotPassword` endpoint in `AuthController`.
- Added necessary DTOs for forgot password.
- Updated tests for the new functionality.

## Changes

1. Added a new method in `AuthService` to handle forgot password logic.
2. Updated `AuthController` to include the forgot password endpoint.
3. Created DTOs for forgot password requests.
4. Added unit tests for the `forgotPassword` method in `AuthService`.

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes.

## Related Issues

Fixes #12

2024-07-24 21:18 UTC, Heba-WebDev commented on .gitignore
Why is .env.local here?

2024-07-24 21:19 UTC, Heba-WebDev commented on src/database/data-source.ts
Why was this changes? Please let it be as it was before

2024-07-24 21:20 UTC, Heba-WebDev commented on src/modules/auth/auth.controller.ts
Please return the nestjs way, look at the docs (or merged PRs).

2024-07-24 21:20 UTC, Heba-WebDev requested changes
I left few comments please fix them

2024-07-24 21:42 UTC, alexindevs commented on .gitignore
I've removed it.

2024-07-24 21:42 UTC, alexindevs commented on src/database/data-source.ts
I've reverted.

2024-07-24 21:42 UTC, alexindevs commented on src/modules/auth/auth.controller.ts
I've fixed it; please review.

2024-07-24 22:29 UTC, Cobidex reviewed
Good Job! Few comments

2024-07-24 22:29 UTC, Cobidex commented on src/modules/otp/otp.service.spec.ts
> +// Mock the generateSixDigitToken function
Dangling comment, best removed

2024-07-24 22:29 UTC, Cobidex commented on src/modules/user/user.service.ts
> +    return await this.userRepository.save(newUser);
No need for await keyword when returning a promise from function. Reduces response time needlessly

2024-07-24 22:44 UTC, Cobidex commented
LGTM

2024-07-24 22:45 UTC, Cobidex approved these changes

2024-07-24 23:13 UTC, Heba-WebDev approved these changes
All good now

2024-07-25 10:14 UTC, Heba-WebDev commented
@alexindevs Please resolve the conflicts

2024-07-25 11:34 UTC, alexindevs commented
On it!

2024-07-25 12:38 UTC, TheCodeGhinux approved these changes

2024-07-25 14:35 UTC, buka4rill commented on .env.local
> +SMTP_HOST=""
remove quotes

2024-07-25 14:36 UTC, buka4rill commented on .env.local
> +SMTP_PASSWORD=""
remove quotes

2024-07-25 14:36 UTC, buka4rill reviewed
few more comments

2024-07-25 14:43 UTC, buka4rill commented on .env.local
> +SERVER_NAME="Boilerplate"
Remove quotes

2024-07-25 14:44 UTC, buka4rill reviewed
another one

2024-07-25 21:20 UTC, buka4rill approved these changes

2024-07-25 21:20 UTC, merged

2024-07-25 21:37 UTC, Homoakin619 commented on src/modules/user/user.service.ts
> +    return this.userRepository.save(newUser);
remove return statement from here.  The return value is not being used