feat: endpoint to fetch single product
hngprojects/hng_boilerplate_nestjs pull request #397
Opened 2024-07-24 21:15 UTC by Leona-cloud

## Description
- This PR implements an endpoint that retrieves information about a single product. The response includes product details such as ID, name, description, price, and availability.

## Linked Issue
This PR addresses the following issue [181](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/181)

## Changes Made
API Endpoint Implementation:

Added a GET request endpoint /api/v1/products/{product-id} to fetch a product using the productId provided by the requesting user.
The endpoint validates that the product exists before sending a success or error response to the user.

## Testing
Added unit tests to cover various scenarios:

Successfully fetched products.
Internal Server error if an invalid productId is sent.
Sending a null value if product does not exist.

## Documentation

API Documentation:

Endpoint: /api/v1/products/{productId}
Method: GET
Request param:
productId: (string) The unique id of a product.

http
GET /api/v1/products/{product-id}
Content-Type: application/json

Successful Response:
```
{
  "status_code": 200,
  "message": "Product fetched successfully",
  "data": {
    "products": {
      "id": "8b252212-ac35-4e82-b679-6e610f87a120",
      "product_name": "Product 1",
      "description": "Description for Product 1",
      "quantity": 10,
      "price": 100,
      "category": "91a760a6-9b3f-4063-b0a6-a3543b0b6b21",
      "created_at": "2024-07-24T17:38:04.532Z",
      "updated_at": "2024-07-24T17:38:04.532Z"
    }
  }
}
```
Error Response (Product not found):
```
{"error":"Product not found","status_code":404}
```
Error Response (Internal Server Error):
```
{"statusCode":500,"message":"Internal server error"}
``

2024-07-24 21:25 UTC, davidolanrewaju commented
Apply openAPI documentation on your routes

2024-07-24 21:30 UTC, Heba-WebDev commented on src/modules/product-category/dto/create-product-category.dto.ts
Why do you have an empty dto? if it's not used, please remove it.

2024-07-24 21:31 UTC, Heba-WebDev commented on src/modules/product-category/product-category.controller.ts
Please remove any endpoint you're not responsible for

2024-07-24 21:31 UTC, Heba-WebDev commented on src/modules/product-category/product-category.service.ts
Please remove these static services

2024-07-24 21:32 UTC, Heba-WebDev commented on src/modules/product-category/tests/product-category.service.spec.ts
If you have a service, write few unit tests for it

2024-07-24 21:35 UTC, Heba-WebDev requested changes
Please take a look at the comments I left

2024-07-24 21:52 UTC, Leona-cloud commented
> Please take a look at the comments I left

I've made an update

2024-07-24 22:38 UTC, davidolanrewaju submitted a review, later dismissed

2024-07-24 22:47 UTC, rugue approved these changes

2024-07-25 02:47 UTC, Homoakin619 commented on db/migrations/1721842630604-migration.ts
> +      `CREATE TABLE "abstract_base_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK
remove the migration for this table. Its an abstract entity and not meant to be migrated into the database

2024-07-25 02:48 UTC, Homoakin619 commented on db/migrations/1721842630604-migration.ts
> +      `CREATE TABLE "abstract_base_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK
remove the migration for this table. Its an abstract entity and not meant to be migrated into the database

2024-07-25 02:49 UTC, Homoakin619 commented on db/migrations/1721842630604-migration.ts
> +    await queryRunner.query(`DROP TABLE "abstract_base_entity"`);
remove the drop query for the abstract_base_entity as well

2024-07-25 02:50 UTC, Homoakin619 commented on src/modules/product-category/product-category.module.ts
this is an empty redundant file. remove it

2024-07-25 07:07 UTC, Leona-cloud commented on src/modules/product-category/product-category.module.ts
I've made changes

2024-07-25 11:16 UTC, Heba-WebDev approved these changes

2024-07-25 21:48 UTC, Homoakin619 commented on src/modules/products/products.service.ts
> +    this.logger.log(`Attempting to retrieve product with id: ${productId}`);
remove this

2024-07-25 21:49 UTC, Homoakin619 commented on src/modules/products/products.service.ts
> +      this.logger.log(`Product with id: ${productId} does not exist`);
remove this as well

2024-07-27 20:23 UTC, Heba-WebDev commented on src/modules/products/entities/product.entity.ts
Please specify the nullability of columns, nullable: true/false

2024-07-27 21:09 UTC, Leona-cloud commented on src/modules/products/entities/product.entity.ts
Okay, done.

2024-07-27 21:18 UTC, Heba-WebDev approved these changes
Looks good to me

2024-07-28 18:56 UTC, davidolanrewaju approved these changes

2024-07-28 23:36 UTC, Cobidex approved these changes

2024-07-28 23:37 UTC, merged