[FEAT]: Implement Sign-in with Token Authentication
hngprojects/hng_boilerplate_nestjs pull request #412
Opened 2024-07-24 22:56 UTC by Timmy-id

##What does this PR do?
- This PR implements an endpoint for requesting for top to login and also logging in with the otp

Added POST /api/v1/auth/login Endpoint: Allows clients to login to their accounts.
Response Handling: Provides appropriate responses for missing or invalid refresh tokens.
Error Handling: Returns specific HTTP status codes and messages based on successful login
#How should this be manually tested?
Register a User:

Use the POST /api/v1/auth/register endpoint to register a new user.

Make a POST request to /api/v1/auth/login with the registered users password and email in the request body
Check the response for appropriate status codes and messages.

Edge Cases:
Test with an invalid email to ensure the endpoint returns a 400 Unauthorized status with the correct message.
Test with an invalid password to ensure the endpoint returns a 401 Unauthorized status with the correct message

Endpoints
Request Sign-In Token:

Description: Generate and send a 6-digit sign-in token to the user's email.
Endpoint: POST /v1/auth/signin-token
#### Request Body:
```
{
  "email": "user@example.com"
}
```

#### Response (Success):
```
    {
      "message": "Sign-in token sent to email",
      "status_code": 200
   }
```

#### Response (Error):

```
   {
     "message": "Failed to send sign-in token",
     "status_code": 400
   }
```

## Verify Sign-In Token:

Description:  Verify the 6-digit sign-in token and log in the user.
Endpoint: POST /v1/auth/verify-signin-token
#### Request Body:
```
   {
     "email": "user@example.com",
     "token": "123456"
   }
 
Response (Success):
```
   {
     "message": "Sign-in successful",
     "token": "JWT token containing user id and email",
     "status_code": 200
   }
```

#### Response (Error):
```
   {
     "message": "Invalid token or email",
     "status_code": 401
   }
```

2024-07-24 23:22 UTC, davidolanrewaju commented
Change your title and PR template to follow the approved standard

2024-07-24 23:23 UTC, davidolanrewaju commented
Also fix your workflow

2024-07-25 04:07 UTC, Timmy-id commented
> Also fix your workflow

Kindly check the updated PR @davidolanrewaju

2024-07-25 20:24 UTC, Heba-WebDev commented on src/modules/auth/auth.controller.ts
response.status(HttpStatus.OK) is not needed in nestjs, change this please

2024-07-25 20:28 UTC, Heba-WebDev requested changes
Left you a comment, please take a look

2024-07-25 21:15 UTC, Timmy-id commented on src/modules/auth/auth.controller.ts
I've fixed it.

2024-07-25 22:32 UTC, Homoakin619 commented on package.json
> -    "bcrypt": "^5.1.1",
why did you remove the package, return it. You shouldn't tamper with configurations

2024-07-25 22:33 UTC, Homoakin619 commented on package.json
> -    "@types/bcrypt": "^5.0.2",
same as this, revert this change

2024-07-25 22:35 UTC, Homoakin619 commented on src/modules/auth/auth.service.ts
> -import * as bcrypt from 'bcrypt';
why did you remove the package

2024-07-25 22:37 UTC, Homoakin619 commented on src/modules/auth/auth.service.ts
why did you tamper with someone else's code ?

2024-07-25 22:38 UTC, Homoakin619 commented on src/modules/auth/auth.service.ts
> +      const salt = await bcrypt.genSalt(10);
why did you tamper with someone's code, revert the changes

2024-07-25 22:39 UTC, Homoakin619 commented on src/modules/auth/auth.service.ts
> -import * as bcrypt from 'bcrypt';
why did you tamper with this, revert it

2024-07-25 22:42 UTC, Homoakin619 commented on src/modules/user/user.service.ts
> -  private async getUserByEmail(email: string) {
why did you choose to tamper with codes

2024-07-26 03:41 UTC, closed without merging

2024-07-26 03:44 UTC, Timmy-id commented
Fixed @Homoakin619

2024-07-26 03:44 UTC, Timmy-id commented
Fixed @Homoakin619