feat: Implement latest blog endpoint
hngprojects/hng_boilerplate_nestjs pull request #413
Opened 2024-07-24 22:58 UTC by JumongComputers

2024-07-24 23:27 UTC, davidolanrewaju commented
Fix the merge conflicts

2024-07-24 23:40 UTC, Heba-WebDev commented on package.json
Why did you change bcrypt to bcryptjs? This is not a personal project, you can't change one dependency with another by yourself

2024-07-24 23:45 UTC, Heba-WebDev requested changes
I'll approve once the conflicts are solved

2024-07-25 15:41 UTC, Heba-WebDev submitted a review, later dismissed
Looks good to me but I'd need @Homoakin619 to take a look as well

2024-07-26 10:38 UTC, JumongComputers commented
@Homoakin619 I have resolved the conflict

2024-08-05 16:14 UTC, closed without merging