feat: export user data
hngprojects/hng_boilerplate_nestjs pull request #418
Opened 2024-07-25 00:07 UTC by nadduli

### What does the PR do?
This PR introduces a new API endpoint to export user data in JSON format. It includes server-side logic for retrieving user data along with their related organisations and converting it into JSON format. 

#### How should this be manually tested?
Send a GET request to `/api/v1/export/user` with the query parameter `userId` set to a valid user ID. 

#### Example: 
GET /api/v1/export/user?userId=12345678-1234-1234-1234-123456789012

#### Checklist of what you did:
- [x] Developed the service logic to retrieve user data including related organisations.
- [x] Implemented the endpoint to export user data as JSON.
- [x] Added Swagger documentation for the new endpoint.
- [x] Handled various error scenarios including missing user ID and user not found.
- [x] Wrote unit tests to verify that the endpoint correctly retrieves and exports user data.
- [x] Tested different scenarios to ensure the endpoint handles edge cases effectively.

#### Reference Issue:
[FEAT] Export User Data Endpoint #138

2024-07-25 00:09 UTC, Heba-WebDev commented on .husky/pre-commit
Please don't change the husky folder

2024-07-25 00:10 UTC, nadduli commented on .husky/pre-commit
okay

2024-07-25 00:12 UTC, Heba-WebDev commented on src/modules/export-user/export-user.controller.ts
Please avoid using res.respond, take a look at nestjs docs to see how responses are handled in nest

2024-07-25 00:12 UTC, Heba-WebDev requested changes
Left you comments

2024-07-25 00:17 UTC, nadduli commented
I will work on it in the morning

2024-07-25 10:48 UTC, nadduli commented
worked on them.

2024-07-27 21:18 UTC, nadduli reviewed
all merge conflicts resolved

2024-07-28 19:09 UTC, davidolanrewaju submitted a review, later dismissed

2024-08-05 16:14 UTC, closed without merging