feat: edit blog post endpoint feature
hngprojects/hng_boilerplate_nestjs pull request #420
Opened 2024-07-25 01:15 UTC by akinwalexander

## API Endpoint: Edit Blog Post

### Description
This API endpoint allows super admins to edit existing blog posts. It validates the input data and updates the blog post securely in the database.

### Endpoint
* **Method:** PUT
* **URL:** `/api/v1/blog/edit/{blog_id}`

### Request Body
```json
{
  "title": "string", // Required
  "excerpt": "string", // Optional
  "tags": ["string"] // Optional
}
```

## Response
* Success (200 OK):
```JSON
{ 
  "message": "Blog successfully updated",
  "id": "int",
  "title": "string",
  "excerpt": "string",
  "updated_at": "Datatime"
}
```

## Acceptance Criteria
 * The endpoint allows only a super admin to edit an existing blog post.
 * The endpoint should be accessible at /api/v1/blog/edit/{blog_id}
 * The endpoint should accept HTTP PUT requests.
 * The API should validate the request payload to ensure the title and other necessary fields is 
 provided.
 * Upon successful validation of the input data, the blog post should be updated in the database securely.
* Return a 200 OK status code on successful request.
## Request body application/json
``` {
  "title": "string",
  "excerpt": "string",
  "tags": ["string"]
}
```
## Success payload
```{ 
  "message": "Blog successfully updated",
  "id": "int",
  "title": "string",
  "excerpt": "string",
  "updated_at": "Datatime"
}
```
## Error payload
```{
  "message": "Unauthorized request",
  "status_code": 401
}
```

## Requirements
- [ ] Implement server-side logic to handle blog post edit submissions.
- [ ] Validate and sanitize incoming data.
- [ ] Update the blog post securely in the database.
- [ ] A 401 error should be sent if an unauthorized user tries to edit a blog

## Expected Outcome
* The API endpoint allows super admin to edit their blog posts via the provided data, ensuring all updates are securely stored and validated.

## Test
- [x] Write unit tests to ensure the blog post edit endpoint validates input correctly and updates the post securely.
- [x] Test various scenarios for editing blog posts (e.g., missing title, empty content, invalid tags).
- [x] Perform security test to ensure unauthorized user can not update a blog post.
- [x] Test various scenarios:
    - Successful editing of an existing blog post
    - Attempting to edit a non existing blog post
    - Attempting to edit a blog post without authentication
    - Attempting to edit a blog post without proper permissions

## Referrence Issue
[Blog Edit](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/136)

2024-07-25 07:18 UTC, rugue requested changes
Pls resolve your merge conflict, Pull from dev branch before making PR

2024-07-25 07:29 UTC, davidolanrewaju commented
And also follow the approved PR template

2024-07-25 07:45 UTC, davidolanrewaju commented on src/modules/blog/controllers/blog.controller.ts
> +  @Put('edit/:id')
Document your routes

2024-07-25 07:46 UTC, davidolanrewaju commented on src/modules/blog/controllers/blog.controller.ts
>    //Other blog method endpoint here
Comments are best removed

2024-07-25 07:47 UTC, davidolanrewaju commented on src/modules/blog/services/blog.service.ts
>    //Other blog service here
Comments are best removed

2024-07-25 11:46 UTC, akinwalexander commented on src/modules/blog/controllers/blog.controller.ts
>    //Other blog method endpoint here
Thank you, they are removed now.

2024-07-26 10:51 UTC, akinwalexander commented on src/modules/blog/controllers/blog.controller.ts
> +  @Put('edit/:id')
Endpoint Documented

2024-07-27 07:16 UTC, TheCodeGhinux commented
Fix conflixts sir

2024-07-27 10:17 UTC, closed without merging