feat: delete product
hngprojects/hng_boilerplate_nestjs pull request #434
Opened 2024-07-25 14:58 UTC by davidolanrewaju

## What does the PR do?
This PR addresses issue #77 by implementing the functionality to delete a single product from the database.

## How should this be manually tested?

#### To test this feature, you can send a DELETE request to the following endpoint:

``` DELETE /api/v1/products/{id} ``` - where {id} is the ID of the product you wish to delete.

### Success Response 
If the product is deleted successfully, you will receive the following response structure:
```
{
  "status_code": 200,
  "message": "Product deleted successfully",
}
```

### "Product Does Not Exist" Response
If the product doesn't exist in the database, the following response will be received:
```
{
	error: 'Product not found',
        message: 'The product with ID ${id} does not exist',
}
```

### Invalid Authentication Response
If the request is made by an unauthenticated or unauthorized user, the following response will be received:
```
{
	"error": "Invalid request",
	"message": "User not authenticated or authorized"
}
```

## Task
- [x] Implement authentication logic to ensure the client is signed in
- [x] Grant user the ability to delete registered products
- [x] Ensure the endpoint correctly identifies if the client is signed in
- [x] Test the endpoint correctly deletes any single product selected by client.

## Referenced Issue
[[FEAT] : Delete product API - Backend](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/77)

2024-07-25 15:07 UTC, Cobidex commented on src/modules/products/entities/product.entity.ts
> +  @ApiProperty()
This decorator should be on the Dto which is the primary interface for exchanging data between the client and the API. It's not meant to be on the entity

2024-07-25 15:08 UTC, Cobidex commented
Your tests are failing.

2024-07-25 15:22 UTC, Cobidex approved these changes

2024-07-25 16:03 UTC, Heba-WebDev commented on src/modules/products/entities/product.entity.ts
I think you should specify if a column is not nullable, especially if you want to enforce this constraint at the database level.

2024-07-25 16:04 UTC, Heba-WebDev requested changes
Please update the dto, the rest looks good to me

2024-07-25 16:14 UTC, Heba-WebDev approved these changes

2024-07-28 23:12 UTC, Heba-WebDev submitted a review, later dismissed

2024-08-05 16:16 UTC, closed without merging