feat: store hng email templates and update create email endpoint
hngprojects/hng_boilerplate_nestjs pull request #618
Opened 2024-08-05 20:24 UTC by King-AJr

2024-08-05 21:50 UTC, Heba-WebDev approved these changes

2024-08-05 21:59 UTC, Homoakin619 submitted a review, later dismissed

2024-08-06 06:23 UTC, Cobidex requested changes

2024-08-06 06:23 UTC, Cobidex commented on src/modules/auth/auth.service.ts
> +    emailData.context = { name: dto.email, recoveryLink: `${process.env.BASE_URL}/auth/reset-password` };
We are not using recovery link for forgot password. We are using otp. Please check the latest update to the dev branch.

2024-08-06 06:23 UTC, Cobidex commented on src/modules/auth/tests/auth.service.spec.ts
> +        recoveryLink: 'http://example.com/auth/reset-password',
Remove the link from the context, only the email and token is required. Leaving it this way will introduce breaking change

2024-08-06 08:50 UTC, Cobidex submitted a review, later dismissed

2024-08-06 17:25 UTC, davidolanrewaju submitted a review, later dismissed

2024-08-08 08:19 UTC, Cobidex approved these changes

2024-08-08 08:19 UTC, merged